### PR TITLE
Use new update/DLC locations introduced in Cemu 1.15.11 (fixes #57)

### LINKED ISSUE #57: Cemu detected a DLC installed at a wrong or outdated location
So how to fix this? If I click yes, on the next launch USB Helper will again unpack DLC to the wrong location.

### PR DESCRIPTION
**Pull request by shiftinv**
Cemu v1.15.11 introduced new paths for update/DLC files ([https://cemu.info/changelog/cemu_1_15_11.txt](https://cemu.info/changelog/cemu_1_15_11.txt)):
* Updates: `mlc01/.../00050000/<titleid[0:8]>`  ->  `mlc01/.../0005000e/<titleid[0:8]>`
* DLC: `mlc01/.../00050000/<titleid[0:8]>/aoc`  ->  `mlc01/.../0005000c/<titleid[0:8]>`

This PR patches `NusHelper.Emulators.Cemu.UpdatePath/.DlcPath` to return these paths and moves the directories from their previous locations to the new ones when using Cemu ≥ 1.15.11.

~~Edit: Do not merge yet, I just found another potential issue with the code that I can't fix right now.~~ Fixed.

### CODE REVIEW

File: USBHelperInjector/Patches/CemuPathPatches.cs [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+using System.Linq;
+using System.Reflection;
+using System.Windows.Forms;
+
+namespace USBHelperInjector.Patches
+{
+    [HarmonyPatch]
+    class CemuUpdatePathPatch
+    {
+        private static readonly object moveLock = new object();
```
Comment (FailedShack) [inline USBHelperInjector/Patches/CemuPathPatches.cs]:
```suggestion
        private static readonly object MOVE_LOCK = new object();
```

Comment (shiftinv) [reply USBHelperInjector/Patches/CemuPathPatches.cs]: Fixed and rebased to 0.17 branch.
